### ISSUE TITLE
close conn is crash on cross compile to android

### ISSUE THREAD

**Issue by centny** [quinn-rs/quinn#1586] opened 2023-06-08 02:35 UTC
<img width="1618" alt="image" src="https://github.com/quinn-rs/quinn/assets/4049551/929cb594-b7c6-4bfe-bb0a-2d75d5324fa0">

## connect
```.rs
  let addr = remote.trim_start_matches("quic://").to_string();
  let domain: &String = json_option_str(&option, "domain").unwrap_or(&addr);
  let addr_conn = wrap_err(addr.parse())?;
  let runtime = quinn::default_runtime().ok_or_else(|| new_message_err("no async runtime found"))?;
  let mut endpoint = quinn::Endpoint::new(quinn::EndpointConfig::default(), None, conn, runtime)?;
  let tls = load_tls_config(self.dir.clone(), &option)?;
  endpoint.set_default_client_config(quinn::ClientConfig::new(tls));
  let conn = wrap_err(endpoint.connect(addr_conn, domain))?.await?;
  let (send, recv) = conn.open_bi().await?;
  let (rx, tx) = wrap_quinn_w(send, recv);
```

**Comment by Ralith** [comment] 2023-06-08 05:25
Please include terminal output and trace logs.

**Comment by centny** [comment] 2023-06-08 13:23
found the reason, the send be closed twice. is it a issue? std tcp stream cant be close multi time

**Comment by Ralith** [comment] 2023-06-08 19:23
Quinn shouldn't panic. Can you provide a minimal reproduction?

**Comment by centny** [comment] 2023-06-09 01:08
yesterday，i split the minimal code and create  test project to find the issue. uploaded to [testquinncrash](https://github.com/centny/testquinncrash), follow readme, it can reproduce it.

**Comment by Ralith** [comment] 2023-06-11 23:35
I think this is a duplicate of https://github.com/quinn-rs/quinn/issues/1569. There's a fix drafted at https://github.com/quinn-rs/quinn/pull/1575.

**Closed** 2023-06-11 23:35 UTC
