### ISSUE TITLE
Stop using unbounded channels

### ISSUE THREAD

**Issue by DemiMarie** [quinn-rs/quinn#1353] opened 2022-05-07 19:21 UTC
Unbounded channels are an anti-pattern, as they can consume an unbounded amount of memory.  It is better to use a bounded channel and handle the case where the channel fills up.

**Comment by Ralith** [comment] 2022-05-07 22:40
This would be fixed by https://github.com/quinn-rs/quinn/pull/1219, which is waiting on delayed ACK support to validate performance improvements (@Matthias247, any chance of seeing your WIP for that soon?)

**Comment by DemiMarie** [comment] 2022-05-08 00:01
Will this require Quinn to own the threads?

**Comment by Ralith** [comment] 2022-05-08 04:18
No.

**Comment by Ralith** [comment] 2023-08-26 23:42
Duplicate of https://github.com/quinn-rs/quinn/issues/599.

**Closed by Ralith** 2023-08-26 23:42 UTC
