### ISSUE TITLE
max_datagram_size() seems to be off by 2

### ISSUE THREAD

**Issue by jfro** [quinn-rs/quinn#1412] opened 2022-09-21 20:05 UTC
Not sure if this should just be documented or if there should be a fix to the calculation.
If I try to send a packet via `send_datagram` of data at the size returned by `max_datagram_size()` I'll get a `Toolarge` error. I've had to reduce it by 2 to get it to pass the check & send the datagram.
I'm `calling max_datagram_size()` at time of data generation & immediate `send_datagram()` call so it should be current.

**Comment by Ralith** [comment] 2022-09-22 03:04
Thanks for the report! We should really have a unit test for this.

**Comment by Ralith** [comment] 2022-09-23 17:28
I'm not able to reproduce this on 0.8 or main. Can you provide a repro?

**Comment by jfro** [comment] 2022-09-23 18:25
I'll try, but my first attempt at a repro for the assertion bug didn't yield the same problem the original code producing this issue is, haven't found what the difference between the 2 is so far.

**Comment by terrarier2111** [comment] 2022-10-04 19:57
I had a similar issue where when i sent a packet with a size of max_datagram_size it wouldn't reach its destination, but when subtracting 1 or more from it, it worked

**Comment by Ralith** [comment] 2022-10-04 20:06
That was https://github.com/quinn-rs/quinn/issues/1413, which was fixed in https://github.com/quinn-rs/quinn/pull/1415.

**Comment by Ralith** [comment] 2023-08-22 02:35
Closing as not reproducible.

**Closed by Ralith** 2023-08-22 02:35 UTC
Labels: bug
