### ISSUE TITLE
Panic with tokio 1.39

### ISSUE THREAD

**Issue by alexheretic** [quinn-rs/quinn#1936] opened 2024-07-23 15:08 UTC
_tokio_ `1.39.0` is out today. It causes _quinn_ to panic. This can be demonstrated using this repos tests. Not sure if this is a _tokio_ issue tbf, but I've so far only seen issue with _quinn_ usage.

## tokio = 1.38.1
No panics (2 test failures locally).
```
failures:
    tests::echo_v6
    tests::local_addr

test result: FAILED. 16 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.88s
```

## tokio = 1.39.0
```
thread 'tests::stream_id_flow_control' panicked at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/util/linked_list.rs:123:9:
assertion `left != right` failed
  left: Some(0x7405e001cca8)
 right: Some(0x7405e001cca8)
thread 'tests::stream_id_flow_control' panicked at quinn/src/mutex.rs:140:42:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5d0d72f99705 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x5d0d72f99705 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5d0d72f99705 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5d0d72f99705 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5d0d72fc7edb - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:     0x5d0d72fc7edb - core::fmt::write::hc090a2ffd6b28c4a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:     0x5d0d72f9630f - std::io::Write::write_fmt::h9443d787e8277bd2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:     0x5d0d72f994de - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5d0d72f994de - std::sys_common::backtrace::print::ha96650907276675e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5d0d72f9ae59 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
  10:     0x5d0d72f9ab1e - std::panicking::default_hook::h207342be97478370
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:295:9
  11:     0x5d0d7289b8da - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::haebd875eeb75949f
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  12:     0x5d0d7289b8da - test::test_main::{{closure}}::h9108cb0ebacdb458
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:137:21
  13:     0x5d0d72f9b496 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha9c3bc81d312fd83
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  14:     0x5d0d72f9b496 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
  15:     0x5d0d72f9b244 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
  16:     0x5d0d72f99bc9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
  17:     0x5d0d72f9af77 - rust_begin_unwind
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
  18:     0x5d0d72fc4c83 - core::panicking::panic_fmt::hdc63834ffaaefae5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  19:     0x5d0d72fc5266 - core::result::unwrap_failed::h82b551e0ff2b2176
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
  20:     0x5d0d726f3f87 - core::result::Result<T,E>::unwrap::h7b758e5cdff3ed22
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1077:23
  21:     0x5d0d726f3f87 - quinn::mutex::non_tracking::Mutex<T>::lock::h71f330de9df87fc6
                               at /home/alex/project/quinn/quinn/src/mutex.rs:140:24
  22:     0x5d0d727b88e7 - <quinn::connection::ConnectionRef as core::ops::drop::Drop>::drop::hef811135937af9fd
                               at /home/alex/project/quinn/quinn/src/connection.rs:893:26
  23:     0x5d0d727b0363 - core::ptr::drop_in_place<quinn::connection::ConnectionRef>::h65cf2a660177cc83
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  24:     0x5d0d727b063a - core::ptr::drop_in_place<quinn::connection::ConnectionDriver>::hbe4e033f7a68486c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  25:     0x5d0d727f5231 - quinn::connection::Connecting::new::{{closure}}::h68ea5f02d748ef3d
                               at /home/alex/project/quinn/quinn/src/connection.rs:66:44
  26:     0x5d0d72826212 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hd4551257fba1b882
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  27:     0x5d0d726dd953 - <core::pin::Pin<P> as core::future::future::Future>::poll::h5b37e4f43ead372e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  28:     0x5d0d72719419 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h713b6db007589c20
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/core.rs:328:17
  29:     0x5d0d727175d1 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h244ad306bd1850b1
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/loom/std/unsafe_cell.rs:16:9
  30:     0x5d0d727175d1 - tokio::runtime::task::core::Core<T,S>::poll::he99f9c7bb5b34dce
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/core.rs:317:13
  31:     0x5d0d7275695a - tokio::runtime::task::harness::poll_future::{{closure}}::hdd0684df72b6f6c9
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/harness.rs:485:19
  32:     0x5d0d726f06e0 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h63e12e3e69290482
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
  33:     0x5d0d7278dd99 - std::panicking::try::do_call::h5b4ac7479926505f
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  34:     0x5d0d72798bbb - __rust_try
  35:     0x5d0d72788f16 - std::panicking::try::ha1be30cc6fe03835
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  36:     0x5d0d726db5fd - std::panic::catch_unwind::h6264b07500dfa44b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  37:     0x5d0d7275101f - tokio::runtime::task::harness::poll_future::hae90569455274681
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/harness.rs:473:18
  38:     0x5d0d727591a5 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h632aa260885b5ef2
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/harness.rs:208:27
  39:     0x5d0d72761ef3 - tokio::runtime::task::harness::Harness<T,S>::poll::h1ffc59ecdcebd2a2
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/harness.rs:153:15
  40:     0x5d0d726e010b - tokio::runtime::task::raw::poll::ha158ab71866e92cf
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/raw.rs:271:5
  41:     0x5d0d72f4d597 - tokio::runtime::task::raw::RawTask::poll::hd536891f62c74f57
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/raw.rs:201:18
  42:     0x5d0d7279e5e1 - tokio::runtime::task::LocalNotified<S>::run::hc2516dc311cd0b22
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/task/mod.rs:427:9
  43:     0x5d0d7281cb5a - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::hda604a19862693e0
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:714:25
  44:     0x5d0d72810413 - tokio::runtime::coop::with_budget::hafb561b888e21170
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/coop.rs:107:5
  45:     0x5d0d72810413 - tokio::runtime::coop::budget::h28777a21c6a62fd6
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/coop.rs:73:5
  46:     0x5d0d72810413 - tokio::runtime::scheduler::current_thread::Context::run_task::{{closure}}::h96270d40531510e7
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:348:43
  47:     0x5d0d7280afd6 - tokio::runtime::scheduler::current_thread::Context::enter::h69dcfcbe0db43a73
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:412:19
  48:     0x5d0d7280f2eb - tokio::runtime::scheduler::current_thread::Context::run_task::h9e21c6d8a4c59dfc
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:348:23
  49:     0x5d0d7281712c - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::h6b3d340b1b30cd96
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:713:35
  50:     0x5d0d72813ecb - tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}::ha49f18d8fc33194c
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:751:68
  51:     0x5d0d726ed97b - tokio::runtime::context::scoped::Scoped<T>::set::hec735a38da7f044a
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/context/scoped.rs:40:9
  52:     0x5d0d72772889 - tokio::runtime::context::set_scheduler::{{closure}}::h5520361a83669e0c
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/context.rs:180:26
  53:     0x5d0d727316f6 - std::thread::local::LocalKey<T>::try_with::haf2e755d8db657e6
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:286:12
  54:     0x5d0d7272bd1a - std::thread::local::LocalKey<T>::with::h039a4b214f6ad586
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:262:9
  55:     0x5d0d7277257d - tokio::runtime::context::set_scheduler::haa50cb973a47493a
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/context.rs:180:9
  56:     0x5d0d728120e0 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::h60b3938de84ed797
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:751:27
  57:     0x5d0d728142dd - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::hc419d107f38499e0
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:660:19
  58:     0x5d0d7280498a - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}::hec72aae76ccb0a7c
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:180:28
  59:     0x5d0d726d63ba - tokio::runtime::context::runtime::enter_runtime::h6bd228a7d3810f6f
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/context/runtime.rs:65:16
  60:     0x5d0d72800dce - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::h0c0fab032f44674e
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/scheduler/current_thread/mod.rs:168:9
  61:     0x5d0d7277054d - tokio::runtime::runtime::Runtime::block_on_inner::h28e3fcf5eaf202ce
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/runtime.rs:361:47
  62:     0x5d0d727720d5 - tokio::runtime::runtime::Runtime::block_on::hbb8ad7b242b8acee
                               at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/runtime/runtime.rs:335:13
  63:     0x5d0d726ffea8 - quinn::tests::stream_id_flow_control::h280f930c66a3c42a
                               at /home/alex/project/quinn/quinn/src/tests.rs:749:5
  64:     0x5d0d727e2017 - quinn::tests::stream_id_flow_control::{{closure}}::h44e7b9ad4a34ce51
                               at /home/alex/project/quinn/quinn/src/tests.rs:733:34
  65:     0x5d0d727a47f6 - core::ops::function::FnOnce::call_once::hc696a24fc903eeab
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  66:     0x5d0d728a02bb - core::ops::function::FnOnce::call_once::hb194ee8411fb46c7
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  67:     0x5d0d728a02bb - test::__rust_begin_short_backtrace::h871a93aaa56c76c5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:623:18
  68:     0x5d0d7289f9c1 - test::run_test_in_process::{{closure}}::h6d9e6b0161cb50c6
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:646:60
  69:     0x5d0d7289f9c1 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb9f3c63b5d0e0baa
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
  70:     0x5d0d7289f9c1 - std::panicking::try::do_call::h83eb4c9b7c70ebcc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  71:     0x5d0d7289f9c1 - std::panicking::try::h5ffd56bf671a89b3
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  72:     0x5d0d7289f9c1 - std::panic::catch_unwind::h044e758d6cbf65b7
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  73:     0x5d0d7289f9c1 - test::run_test_in_process::hf7ca2db08c9223b8
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:646:27
  74:     0x5d0d7289f9c1 - test::run_test::{{closure}}::h9657c20462181b87
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:569:43
  75:     0x5d0d728671f4 - test::run_test::{{closure}}::h80c3aef427ce62cc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:597:41
  76:     0x5d0d728671f4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h43274eec75e29097
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
  77:     0x5d0d7286bc62 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hea1335728d2a7953
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:542:17
  78:     0x5d0d7286bc62 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb16d5d5fd985753c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
  79:     0x5d0d7286bc62 - std::panicking::try::do_call::h65de05e16c44e167
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  80:     0x5d0d7286bc62 - std::panicking::try::h187f01afe14eb3bf
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  81:     0x5d0d7286bc62 - std::panic::catch_unwind::h1b55347b2c8efb63
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  82:     0x5d0d7286bc62 - std::thread::Builder::spawn_unchecked_::{{closure}}::hea39e0adaff5b52d
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:541:30
  83:     0x5d0d7286bc62 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9b61aba01c3c1f32
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  84:     0x5d0d72f9fd6b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h09e5a4c541afa800
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
  85:     0x5d0d72f9fd6b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9c8b03c22f4e7026
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
  86:     0x5d0d72f9fd6b - std::sys::pal::unix::thread::Thread::new::thread_start::h522bc89a54da820a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys/pal/unix/thread.rs:108:17
  87:     0x74061ce94ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  88:     0x74061cf26850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  89:                0x0 - <unknown>
thread 'tests::stream_id_flow_control' panicked at library/core/src/panicking.rs:228:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `-p quinn --lib`

Caused by:
  process didn't exit successfully: `/home/alex/.cache/cargo/target/debug/deps/quinn-57894a3fca715ede` (signal: 6, SIGABRT: process abort signal
```

**Comment by djc** [comment] 2024-07-23 15:42
What platform are you testing on? Looks like Linux probably? I'm surprised those tests fail for you, they pass for me at least.

I can reproduce this issue on macOS, works with tokio 1.37.0 (that's what I had before) and fails with tokio 1.39.0.

**Comment by Darksonn** [comment] 2024-07-23 15:49
Are you able to try this with https://github.com/tokio-rs/tokio/pull/6584 reverted?

**Comment by alexheretic** [comment] 2024-07-23 15:53
> Are you able to try this with [tokio-rs/tokio#6584](https://github.com/tokio-rs/tokio/pull/6584) reverted?

@Darksonn with `8480a18` reverted there is no panic running quinn. I guess this means this is a tokio issue after all. I'll raise one there.

**Comment by alexheretic** [comment] 2024-07-23 15:56
> What platform are you testing on? Looks like Linux probably? I'm surprised those tests fail for you, they pass for me at least.

@djc yep linux `Linux alex-XPS-15-9520 6.5.0-44-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by alexheretic** [comment] 2024-07-23 16:04
You can ignore my test failures. My work laptop is setup has `/proc/sys/net/ipv6/conf/all/disable_ipv6` `1` for some reason :shrug:

**Comment by djc** [comment] 2024-07-23 16:31
Closing this since it was a Tokio regression:

https://github.com/tokio-rs/tokio/pull/6715

**Closed** 2024-07-23 16:30 UTC

**Comment by alexheretic** [comment] 2024-07-23 16:37
Yep I can confirm all seems well here with tokio 1.39.1 :heavy_check_mark:

**Comment by djc** [comment] 2024-07-23 16:41
Thanks for the quick feedback!
