### ISSUE TITLE
`handshakecorruption` crash

### ISSUE THREAD

**Issue by larseggert** [quinn-rs/quinn#1942] opened 2024-07-25 20:38 UTC
https://github.com/mozilla/neqo/actions/runs/10096708958/job/27920055350#step:6:735
```client  | thread 'main' panicked at 'driver: h3::Error { timeout: true }', src/bin/client.rs:175:18
client  | stack backtrace:
client  |    0: rust_begin_unwind
client  |              at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
client  |    1: core::panicking::panic_fmt
client  |              at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
client  |    2: core::result::unwrap_failed
client  |              at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
client  |    3: client::main::{{closure}}
client  |    4: tokio::runtime::park::CachedParkThread::block_on
client  |    5: tokio::runtime::runtime::Runtime::block_on
client  |    6: client::main
client  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by djc** [comment] 2024-07-25 21:38
Looks like it might be related to #1938?

**Comment by Ralith** [comment] 2024-07-25 23:43
The link seems to be a failure in the h3 test, not handshakecorruption? Scrolling up, that case ("C1") is reported as passing:

```
+-------+----------------------------------------------+
|       |                 neqo-latest                  |
+-------+----------------------------------------------+
| quinn | ✓(H,DC,LR,C20,M,S,R,Z,B,U,E,A,L1,L2,C1,C2,6) |
|       |                     ?()                      |
|       |                   ✕(3,V2)                    |
+-------+----------------------------------------------+
```

As for why it's failing, you clipped the key line:
```
client  | thread 'main' panicked at 'driver: h3::Error { timeout: true }', src/bin/client.rs:175:18
```
Looks like that reproduces. I'm not familiar with the h3 stack, but I'll take a quick look anyway.

**Comment by Ralith** [comment] 2024-07-25 23:52
Fixed by https://github.com/quinn-rs/quinn-interop/pull/12.

**Closed by Ralith** 2024-07-25 23:52 UTC

**Comment by Ralith** [comment] 2024-07-25 23:53
Note that we *do* have a `handshakecorruption` failure (not crash) in the current version. This is fixed by https://github.com/quinn-rs/quinn/pull/1937, which we'll include in a maintenance release soon.

**Comment by larseggert** [comment] 2024-07-26 00:41
Sorry I got getting the test name wrong, but glad you managed to fix it quickly in any case!
