### ISSUE TITLE
New default value of 'max_concurrent_uni_streams'

### ISSUE THREAD

**Issue by bochaco** [quinn-rs/quinn#1061] opened 2021-03-10 21:04 UTC
I'm having issues after upgrading from v0.6.1 to v0.7.0 with sending many messages over uni-streams and I don't get to understand what could be happening.

From looking at https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/config.rs#L229 it seems by default now this is set to 100, which in v0.6.1 it was by default set to infinite, is this correct?

Then, looking at the example  https://github.com/quinn-rs/quinn/blob/main/quinn/examples/server.rs#L67 I'm getting the idea that is setting it to be infinite, is this correct?

In a crate I'm working on, when setting this config to 0 somehow is causing that our "server" side app cannot accept any message, and when default is used it can accept up to 100 but then something is going on that we cannot send more than that even after invoking `finish` in the uni-stream used.
Is there anything I should consider in particular to be able to set this config to "infinite" in an attempt to have it behave the same as in previous v0.6.1?

**Comment by Ralith** [comment] 2021-03-10 21:25
> it seems by default now this is set to 100, which in v0.6.1 it was by default set to infinite, is this correct?

Basically, yeah. Previously we had a "max streams waiting for accept" limit, but we determined that "max concurrent streams" is more useful, since applications that wish to consume bounded resources (i.e. most reasonable applications) would otherwise need to reinvent that themselves. You could set it to `VarInt::MAX` to effectively disable it for testing purposes or if you're certain clients are well-behaved.

> I'm getting the idea that is setting it to be infinite, is this correct?

No, setting that figure to 0 means you may have at most zero concurrent streams, which will disable accepting that type of stream entirely, i.e. the behavior you observe is intended.

> we cannot send more than [100] even after invoking finish in the uni-stream used.

Does the receiving application read the streams all the way to the end? If so, this may be a bug; do you have a repro?

**Comment by bochaco** [comment] 2021-03-11 04:46
> Does the receiving application read the streams all the way to the end?

This seems like could be the issue I'm facing, let me research a bit more to confirm, and/or to share some test to reproduce it, but I just gave it a quick try to `stop` the `RecvStream` after reading (since I'm reading with `read_exact` only) and things look much better. I'll get back to you with more info.

**Comment by bochaco** [comment] 2021-03-11 05:24
> Does the receiving application read the streams all the way to the end?

This is likely the issue I'm facing, I just gave it a quick try and things look better by making sure the `RecvStream` is read till the end. Let me either confirm or get back to you with some snippet to reproduce it if not.

**Comment by Ralith** [comment] 2021-03-11 06:04
On inspection, I think we do have a bug here: streams are not being freed when stopped after a FIN bit is received. Reading all the way to the end will work around the issue; I'll get a fix drafted shortly.

**Comment by Ralith** [comment] 2021-03-11 06:28
A fix has been drafted. With this, your original code that uses read_exact and then drops the stream should behave as intended.

**Closed** 2021-03-11 06:46 UTC

**Comment by lionel1704** [comment] 2021-03-11 07:04
Thanks for the quick action team! I tested quinn 0.7.0 + the fix with the crate that @bochaco mentioned in the OP and it's now working as expected. 

Will there be a patch release of quinn with this fix?

**Comment by djc** [comment] 2021-03-11 12:22
I think a bugfix release for this makes sense, see #1063.

**Comment by bochaco** [comment] 2021-03-11 13:41
Thanks a lot @Ralith !

> streams are not being freed when stopped after a FIN bit is received

I can confirm this was an issue too, last night when trying to make sure the stream is read till the end I gave a try to `stop` the RecvStream after reading with `read_exact` and that wasn't solving the issue, and I was actually doubting why that wouldn't solve it as well, so just to confirm.

**Comment by Ralith** [comment] 2021-03-11 17:54
Thanks for validating!

**Comment by Ralith** [comment] 2021-03-11 18:01
> I was actually doubting why [stop] wouldn't solve it as well, so just to confirm.

For reference, the `Drop` impl for receive streams implicitly calls `stop` if you haven't actually seen the end of the stream yet, so it's expected that this would have bug-for-bug identical behavior.

**Comment by bochaco** [comment] 2021-03-11 18:04
Makes sense, thanks!
